
server:
  port: 8083 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://39.108.93.119:3306/school_bus?serverTimeZone=UTC&useSSL=false&characterEncoding=UTF-8
      url: jdbc:mysql://localhost:3306/schoolBus?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
      username: root
      password: cp123456789
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 3000
        timeBetweenEvictionRunsMillis: 60000
        pool-prepared-statements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        web-stat-filter:
          enabled: true
          url-pattern: "/*"
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        stat-view-servlet:
          login-username: admin
          login-password: 123
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: 123
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sb-order.log

dubbo:
  application:
    name: guns-order
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    port: 20883
  metadata-report:
    address: zookeeper://127.0.0.1:2181

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: orderProducerGroup # 生产消息的组

mq:
  order:
    consumer:
      group:
        name: orderTopic_cancel_group
    topic: orderTopic # 话题：订单话题
