rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key
  ignore-url: /user/register,/user/check,/swagger,/v2,/webjars,/seats,/bus,/file,/druid
server:
  port: 8087 #项目端口


spring:
  application:
    name: gateway
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/schoolBus?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
      username: root
      password: cp123456789
      filters: log4j,wall,mergeStat
      type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: 123
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
  cloud:
    sentinel:
      eager: true
      transport:
        port: 8092
        dashboard: 127.0.0.1:8091
logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sb-gateway.log

dubbo:
  application:
    name: guns-gateway
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181


swagger:
  enable: true
